return {
    {
        "nvim-treesitter/nvim-treesitter",
        build = function()
            require("nvim-treesitter.install").update({ with_sync = false })()
        end,
        run = ":TSUpdate",
        lazy = false,
        config = function()
            require("nvim-treesitter.install").compilers = { "clang" }
            require("nvim-treesitter.configs").setup({
                ensure_installed = {
                    "angular",
                    "asm",
                    "astro",
                    "bash",
                    "bibtex",
                    "c",
                    "cmake",
                    "comment",
                    "commonlisp",
                    "cpp",
                    "css",
                    "csv",
                    "diff",
                    "dockerfile",
                    "elm",
                    "go",
                    "haskell",
                    "html",
                    "java",
                    "javascript",
                    "jsdoc",
                    "json",
                    "json5",
                    "latex",
                    "llvm",
                    "lua",
                    "make",
                    "markdown",
                    "ocaml",
                    "perl",
                    "php",
                    "powershell",
                    "prisma",
                    "prolog",
                    "psv",
                    "pug",
                    "purescript",
                    "python",
                    "requirements",
                    "robots",
                    "rust",
                    "scheme",
                    "scss",
                    "sql",
                    "styled",
                    "svelte",
                    "toml",
                    "tsv",
                    "tsx",
                    "typescript",
                    "vim",
                    "vimdoc",
                    "vue",
                    "xml",
                    "yaml",
                    "zig",
                },
                sync_install = true,
                auto_install = true,
                highlight = { enable = true },
                indent = { enable = true },
            })
        end,
    },
}
